# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rack-useragent"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sergio Gil", "Luismi Cavall\u{e9}", "Claes Wallin (\u{97cb}\u{5609}\u{8aa0})"]
  s.date = "2013-06-13"
  s.email = "claes.wallin@greatsinodevelopment.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "NEWS.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/rack/user_agent.rb",
    "lib/rack/user_agent/filter.rb",
    "rack-useragent.gemspec",
    "test/public/upgrade.es.html",
    "test/public/upgrade.html",
    "test/upgrade.erb",
    "test/user_agent_filter_test.rb"
  ]
  s.homepage = "http://github.com/clacke/rack-useragent"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "Rack Middleware for filtering by user agent"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 0.9.1"])
      s.add_runtime_dependency(%q<useragent>, [">= 0.1.4"])
    else
      s.add_dependency(%q<rack>, [">= 0.9.1"])
      s.add_dependency(%q<useragent>, [">= 0.1.4"])
    end
  else
    s.add_dependency(%q<rack>, [">= 0.9.1"])
    s.add_dependency(%q<useragent>, [">= 0.1.4"])
  end
end

